import type { Question } from "../data/onchainSurvivalQuestions";
import type { AttributionStatus, BadgeStatus } from "../types";
import { BadgeClaimPanel, IQHolderPanel, PitchModePanel } from "./UI";

export function resultTier(score: number) {
  if (score <= 2) return ["Exit Liquidity", "You did not survive the group chat alpha."];
  if (score <= 5) return ["Airdrop Tourist", "You know the words, but the wallet drainer still has a chance."];
  if (score <= 8) return ["DeFi Survivor", "You probably revoked at least one approval in your life."];
  return ["Terminally Onchain", "You read contract permissions and still somehow ape."];
}

export function ResultScreen(props: { score: number; xp: number; mistakes: Question[]; connected: boolean; verified: boolean; badgeStatus: BadgeStatus; attribution: AttributionStatus; onReview: () => void; onAgain: () => void; onCheck: () => void; onFeature: (title: string) => void; onClaim: () => void; onAttribution: () => void; onWiki: (q?: Question) => void; onSponsored: (title: string) => void; onPitch: (title: string) => void }) {
  const [title, copy] = resultTier(props.score);
  return <main className="space-y-4 px-3 pb-8 pt-4"><section className="hero-card text-center"><div className="mx-auto grid size-20 place-items-center rounded-3xl bg-gradient-to-br from-iq to-base text-2xl font-black text-ink">{props.score}/10</div><p className="mt-5 eyebrow text-iq">Result tier</p><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-white/55">{copy}</p><div className="mt-4 flex justify-center gap-2"><span className="chip text-lime">✦ {props.xp} XP</span><span className="chip">{props.score * 10}% survival</span></div></section><div className="grid grid-cols-2 gap-2">{props.mistakes.length ? <button className="btn-primary" onClick={props.onReview}>Review mistakes</button> : <button className="btn-primary" onClick={() => props.onWiki()}>Flawless deep dive</button>}<button className="btn-secondary" onClick={props.onAgain}>Practice again</button></div><section className="section-card"><p className="eyebrow text-iq">IQ.wiki deep dives</p><div className="mt-3 space-y-2">{(props.mistakes.length ? props.mistakes.slice(0, 3) : []).map(q => <button key={q.id} className="tap-card w-full text-left" onClick={() => props.onWiki(q)}><strong className="text-sm">{q.title}</strong><span className="mt-1 block text-xs text-white/40">Open learning context →</span></button>)}{!props.mistakes.length && <button className="tap-card w-full text-left" onClick={() => props.onWiki()}><strong>Explore IQ.wiki</strong></button>}</div></section><BadgeClaimPanel connected={props.connected} lessonComplete status={props.badgeStatus} attribution={props.attribution} onClaim={props.onClaim} onAttribution={props.onAttribution} /><IQHolderPanel connected={props.connected} verified={props.verified} onCheck={props.onCheck} onFeature={props.onFeature} /><section className="section-card"><p className="eyebrow text-base">Sponsored protocol paths</p><div className="mt-3 space-y-2">{["Borrow Without Getting Liquidated", "Spot Bad Liquidity", "Detect Oracle Risk", "Survive a Depeg", "Avoid the Wallet Drainer"].map(title => <button key={title} className="tap-card w-full text-left text-sm font-bold" onClick={() => props.onSponsored(title)}>{title}<span className="float-right text-white/30">→</span></button>)}</div></section><PitchModePanel onItem={props.onPitch} /></main>;
}

export function MistakeReview({ questions, answers, onBack, onAgain, onWiki }: { questions: Question[]; answers: Record<string, string>; onBack: () => void; onAgain: () => void; onWiki: (q: Question) => void }) {
  const mistakes = questions.filter(q => answers[q.id] !== q.correctAnswerId);
  return <main className="space-y-4 px-3 pb-8 pt-4"><section className="hero-card"><p className="eyebrow text-iq">Advanced mistake review</p><h1 className="mt-2 text-3xl font-black">Patch the weak spots.</h1><p className="mt-2 text-sm text-white/50">{mistakes.length} scenarios to revisit.</p></section>{mistakes.map(q => <section key={q.id} className="section-card"><span className="chip">{q.difficulty}</span><h2 className="mt-3 font-black">{q.title}</h2><p className="mt-3 text-xs text-red-200">You picked: {q.answers.find(a => a.id === answers[q.id])?.text}</p><p className="mt-2 text-xs text-lime">Best move: {q.answers.find(a => a.id === q.correctAnswerId)?.text}</p><p className="mt-3 text-sm leading-6 text-white/55">{q.explanation}</p><button className="btn-secondary mt-4" onClick={() => onWiki(q)}>Deepen this on IQ.wiki</button></section>)}<div className="grid grid-cols-2 gap-2"><button className="btn-primary" onClick={onAgain}>Practice again</button><button className="btn-secondary" onClick={onBack}>Results</button></div></main>;
}
