import type { Question } from "../data/onchainSurvivalQuestions";
import { BADGE_NAME, MOCK_BUILDER_CODE } from "../lib/badge";
import type { AttributionStatus, BadgeStatus } from "../types";

export function ProgressBar({ current, total }: { current: number; total: number }) {
  return <div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-iq to-base transition-all duration-500" style={{ width: `${(current / total) * 100}%` }} /></div>;
}
export function XPDisplay({ xp }: { xp: number }) { return <span className="chip text-lime">✦ {xp} XP</span>; }
export function StreakDisplay({ streak }: { streak: number }) { return <span className="chip text-orange-300">▲ {streak}</span>; }

export function QuestionCard({ question, selectedId, onAnswer }: { question: Question; selectedId: string | null; onAnswer: (id: string) => void }) {
  return <section><div className="mb-4 flex items-center justify-between"><span className="chip">{question.difficulty}</span><span className="text-xs font-bold text-lime">+{question.xpReward} XP</span></div><h1 className="text-2xl font-black leading-tight">{question.title}</h1><p className="mt-3 text-sm leading-6 text-white/60">{question.scenario}</p><div className="mt-5 space-y-3">{question.answers.map((answer, i) => { const state = !selectedId ? "" : answer.id === question.correctAnswerId ? "border-lime/60 bg-lime/10 text-lime" : answer.id === selectedId ? "border-red-400/60 bg-red-400/10 text-red-200" : "opacity-35"; return <button key={answer.id} disabled={Boolean(selectedId)} onClick={() => onAnswer(answer.id)} className={`tap-card flex w-full items-start gap-3 text-left ${state}`}><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-white/10 text-xs font-black">{String.fromCharCode(65 + i)}</span><span className="text-sm font-semibold leading-6">{answer.text}</span></button>; })}</div></section>;
}

export function FeedbackCard({ correct, explanation, final, onContinue, onWiki }: { correct: boolean; explanation: string; final: boolean; onContinue: () => void; onWiki: () => void }) {
  return <section className={`mt-5 rounded-3xl border p-4 ${correct ? "border-lime/30 bg-lime/10" : "border-red-400/30 bg-red-400/10"}`}><strong className={correct ? "text-lime" : "text-red-200"}>{correct ? "Correct. You may survive another epoch." : "Not quite. This is how you become someone else’s yield."}</strong><p className="mt-2 text-sm leading-6 text-white/60">{explanation}</p><button className="btn-secondary mt-4" onClick={onWiki}>Deepen this on IQ.wiki</button><button className="btn-primary mt-2" onClick={onContinue}>{final ? "See results" : "Next scenario"}</button></section>;
}

export function AccountPanel({ connected, verified, onConnect, onReset }: { connected: boolean; verified: boolean; onConnect: () => void; onReset: () => void }) {
  return <section className="section-card"><div className="flex items-center justify-between"><div><p className="eyebrow text-base">Base Account</p><h2 className="mt-1 text-lg font-black">{connected ? "0xIQ...Dojo" : "Connect the simulator"}</h2></div><span className={`chip ${connected ? "text-lime" : ""}`}>{connected ? "Connected" : "Offline"}</span></div>{connected && <div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="stat">Network<strong>Base</strong></span><span className="stat">Balance<strong>2,500 IQ</strong></span><span className="stat col-span-2">Access<strong className="text-lime">{verified ? "IQ Holder Verified" : "Checking"}</strong></span></div>}<button className={connected ? "btn-secondary mt-4" : "btn-primary mt-4"} onClick={connected ? onReset : onConnect}>{connected ? "Reset simulator" : "Connect Base Account"}</button></section>;
}

export function IQHolderPanel({ connected, verified, onCheck, onFeature }: { connected: boolean; verified: boolean; onCheck: () => void; onFeature: (title: string) => void }) {
  const features = ["Pro Mode", "Special result titles", "Advanced mistake review", "Badge variant", "Bonus daily challenge"];
  return <section className="section-card"><p className="eyebrow text-iq">IQ Holder Unlocks</p><div className="mt-2 flex items-end justify-between"><div><h2 className="text-xl font-black">{verified ? "IQ Holder Verified" : "1,000 IQ required"}</h2><p className="mt-1 text-xs text-white/45">{connected ? "Simulated balance: 2,500 IQ" : "Connect to simulate the balance check."}</p></div>{verified && <span className="text-2xl">✓</span>}</div><div className="mt-4 grid grid-cols-2 gap-2">{features.map((title, i) => <button key={title} onClick={() => onFeature(title)} className={`tap-card min-h-20 text-left text-xs font-bold ${verified ? "border-lime/30 bg-lime/[0.07]" : ""} ${i === features.length - 1 ? "col-span-2" : ""}`}><span className={verified ? "text-lime" : "text-white/35"}>{verified ? "Unlocked" : "Locked"}</span><strong className="mt-1 block text-white">{title}</strong></button>)}</div><button className="btn-secondary mt-4" onClick={onCheck}>{verified ? "View Pro Mode unlock" : "Simulate IQ check"}</button></section>;
}

const stages: Record<BadgeStatus, string> = { idle: "Ready for attribution", preparing: "Preparing transaction", attributing: "Adding Builder Code attribution", minting: "Minting badge on Base", claimed: "Simulated attributed transaction" };
export function BadgeClaimPanel({ connected, lessonComplete, status, attribution, onClaim, onAttribution }: { connected: boolean; lessonComplete: boolean; status: BadgeStatus; attribution: AttributionStatus; onClaim: () => void; onAttribution: () => void }) {
  const busy = ["preparing", "attributing", "minting"].includes(status);
  return <section className="section-card overflow-hidden"><div className="flex gap-4"><div className="grid size-20 shrink-0 place-items-center rounded-3xl border border-base/50 bg-gradient-to-br from-base/50 to-iq/30 text-2xl font-black">IQ</div><div><p className="eyebrow text-base">Claim IQ Dojo Badge on Base</p><h2 className="mt-1 font-black">{BADGE_NAME}</h2><p className="mt-1 text-xs text-white/45">{lessonComplete ? "Lesson complete. Simulate the future claim." : "Complete today’s lesson to unlock the claim."}</p></div></div><button className="tap-card mt-4 w-full text-left" onClick={onAttribution}><span className="text-[10px] font-black uppercase tracking-wider text-base">{stages[status]}</span><p className="mt-2 text-xs leading-5 text-white/55">IQ Dojo → Badge claim → Builder Code <strong>{MOCK_BUILDER_CODE}</strong> → Base.dev analytics</p>{status === "claimed" && <p className="mt-2 text-xs font-bold text-lime">Base · {MOCK_BUILDER_CODE} · Simulated claim complete</p>}<span className="mt-2 block text-[10px] text-white/35">Attribution state: {attribution}</span></button><button disabled={busy} className="btn-primary mt-4 disabled:opacity-50" onClick={onClaim}>{busy ? stages[status] : status === "claimed" ? "View simulated badge claim" : !connected ? "Connect Base Account to claim" : !lessonComplete ? "Coming next: complete lesson to claim" : "Claim simulated Base badge"}</button></section>;
}

export function PitchModePanel({ onItem }: { onItem: (title: string) => void }) {
  return <section className="section-card"><p className="eyebrow text-iq">Pitch mode</p><h2 className="mt-1 text-xl font-black">Why this loop works</h2><div className="mt-4 grid grid-cols-2 gap-2">{["Product loop", "IQ layer", "Base layer", "Business layer"].map(item => <button key={item} className="tap-card text-left text-xs font-bold" onClick={() => onItem(item)}>{item}<span className="mt-1 block text-white/35">Tap to explain →</span></button>)}</div></section>;
}
